# This file was generated by GoReleaser. DO NOT EDIT.
cask "helm-snoop" do
  name "helm-snoop"
  desc "Detect unused and undefined values in Helm charts"
  homepage "https://github.com/y0-l0/helm-snoop"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "helm-snoop"

  on_macos do
    on_intel do
      url "https://github.com/Y0-L0/helm-snoop/releases/download/v#{version}/helm-snoop_#{version}_darwin_amd64.tar.gz"
      sha256 "3ede4c8a29936ec4cafb7810c80a9656892a9a91d1b22d100bbc4247724782f4"
    end
    on_arm do
      url "https://github.com/Y0-L0/helm-snoop/releases/download/v#{version}/helm-snoop_#{version}_darwin_arm64.tar.gz"
      sha256 "53a1481d3ffde1a11746917c76c27f87ccdf8685702e2edbf4995b0183ec80f8"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/Y0-L0/helm-snoop/releases/download/v#{version}/helm-snoop_#{version}_linux_amd64.tar.gz"
      sha256 "1bbd8aed1d0414c156cd3fbc795819a73a678816a67703d0bbfde300bf2a4ee5"
    end
    on_arm do
      url "https://github.com/Y0-L0/helm-snoop/releases/download/v#{version}/helm-snoop_#{version}_linux_arm64.tar.gz"
      sha256 "39d6835637f0ab0380c36c181050b0f41b09238596b826a964c065b3322e5df0"
    end
  end

  # No zap stanza required
end
