# This file was generated by GoReleaser. DO NOT EDIT.
cask "helm-snoop" do
  name "helm-snoop"
  desc "Detect unused and undefined values in Helm charts"
  homepage "https://github.com/y0-l0/helm-snoop"
  version "0.7.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "helm-snoop"

  on_macos do
    on_intel do
      url "https://github.com/Y0-L0/helm-snoop/releases/download/v#{version}/helm-snoop_#{version}_darwin_amd64.tar.gz"
      sha256 "5371d29d2d7e8cb3668ba6003ea32e32f89dcdb3db327e8c449ed0bfc127fe90"
    end
    on_arm do
      url "https://github.com/Y0-L0/helm-snoop/releases/download/v#{version}/helm-snoop_#{version}_darwin_arm64.tar.gz"
      sha256 "5666564289bdf53c9c08be7bccf79c88b9cf74ce01be5436300aed084de8d583"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/Y0-L0/helm-snoop/releases/download/v#{version}/helm-snoop_#{version}_linux_amd64.tar.gz"
      sha256 "b79aa3869588bf066d5534b75319489dd821f3a75230a7526dcf457562e8942b"
    end
    on_arm do
      url "https://github.com/Y0-L0/helm-snoop/releases/download/v#{version}/helm-snoop_#{version}_linux_arm64.tar.gz"
      sha256 "408492aca77a9b2a1a8033625293e333e6b739390b0096ac523d4df06fac842c"
    end
  end

  # No zap stanza required
end
