# This file was generated by GoReleaser. DO NOT EDIT.
cask "helm-snoop" do
  name "helm-snoop"
  desc "Detect unused and undefined values in Helm charts"
  homepage "https://github.com/y0-l0/helm-snoop"
  version "0.2.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "helm-snoop"

  on_macos do
    on_intel do
      url "https://github.com/Y0-L0/helm-snoop/releases/download/v#{version}/helm-snoop_#{version}_darwin_amd64.tar.gz"
      sha256 "5d8c17c0ed44e2a1035bf1e79575cb7c56a42ff61da541f087f5629e50d1082e"
    end
    on_arm do
      url "https://github.com/Y0-L0/helm-snoop/releases/download/v#{version}/helm-snoop_#{version}_darwin_arm64.tar.gz"
      sha256 "b699710f9db1325f9e9eb928262eef938f69e9010c453e4b40cc1b191bf005d8"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/Y0-L0/helm-snoop/releases/download/v#{version}/helm-snoop_#{version}_linux_amd64.tar.gz"
      sha256 "2a15e10d4444ca0be6619cda8023ef29b2a746d7b5341e4ede3900deb045a802"
    end
    on_arm do
      url "https://github.com/Y0-L0/helm-snoop/releases/download/v#{version}/helm-snoop_#{version}_linux_arm64.tar.gz"
      sha256 "4bd9feef3f703d27491cd12f25415745df5dd7a59df58d64bd25969b924f0376"
    end
  end

  # No zap stanza required
end
