# This file was generated by GoReleaser. DO NOT EDIT.
cask "kubesleep" do
  name "kubesleep"
  desc "Suspend and wake Kubernetes workloads on a schedule"
  homepage "https://github.com/Y0-L0/kubesleep"
  version "0.5.3-next4"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kubesleep"

  on_linux do
    on_intel do
      url "https://github.com/Y0-L0/kubesleep/releases/download/v#{version}/kubesleep_#{version}_linux_amd64.tar.gz"
      sha256 "b5b04c86afee14f48acff6f8c397107b2d0ef36f6aa4806352fd698333246735"
    end
  end

  # No zap stanza required
end
