# This file was generated by GoReleaser. DO NOT EDIT.
cask "kubesleep" do
  name "kubesleep"
  desc "Suspend and wake Kubernetes workloads on a schedule"
  homepage "https://github.com/Y0-L0/kubesleep"
  version "0.5.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kubesleep"

  on_macos do
    on_intel do
      url "https://github.com/Y0-L0/kubesleep/releases/download/v#{version}/kubesleep_#{version}_darwin_amd64.tar.gz"
      sha256 "172d33d8f54e330ba6c91380d49ec56a4a78c1d65dc24db84b20a0928eb7c53e"
    end
    on_arm do
      url "https://github.com/Y0-L0/kubesleep/releases/download/v#{version}/kubesleep_#{version}_darwin_arm64.tar.gz"
      sha256 "4f511e0caaea22248c1fb3a3d9c2d35157fe3ea3fb87172e1e90e4c7b25046e0"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/Y0-L0/kubesleep/releases/download/v#{version}/kubesleep_#{version}_linux_amd64.tar.gz"
      sha256 "4e12094bfa6ab389e62195730423e42ba01a7ad54d2b52e571cbaf57fdfc2698"
    end
    on_arm do
      url "https://github.com/Y0-L0/kubesleep/releases/download/v#{version}/kubesleep_#{version}_linux_arm64.tar.gz"
      sha256 "c0cfc28419ebc8a88260360adc7b3bc6f6dee734cbe29a0a3a9ae6c1853fad5c"
    end
  end

  # No zap stanza required
end
